// Auto-generated by GenerateLocalizationKeys
public static class LocalizationKeys
{
    public static class UI
    {
        public static class Menu
        {
            public const string Start = "UI.Menu.Start";
            public const string Settings = "UI.Menu.Settings";
            public const string Quit = "UI.Menu.Quit";
        }
        public static class Pause
        {
            public const string Resume = "UI.Pause.Resume";
            public const string Quit = "UI.Pause.Quit";
        }
        public static class Settings
        {
            public const string Language = "UI.Settings.Language";
            public const string Volume = "UI.Settings.Volume";
            public const string Graphics = "UI.Settings.Graphics";
        }
        public static class Stats
        {
            public const string Life = "UI.Stats.Life";
            public const string Energy = "UI.Stats.Energy";
        }
        public static class Actions
        {
            public const string Yes = "UI.Actions.Yes";
            public const string No = "UI.Actions.No";
            public const string Use = "UI.Actions.Use";
            public const string Cancel = "UI.Actions.Cancel";
        }
    }
    public static class Gameplay
    {
        public static class Abilities
        {
            public static class Toxic
            {
                public const string Name = "Gameplay.Abilities.Toxic.Name";
            }
        }
        public static class Effects
        {
            public static class Toxic
            {
                public const string Name = "Gameplay.Effects.Toxic.Name";
            }
        }
        public static class Cards
        {
            public static class ToxicCard
            {
                public const string Name = "Gameplay.Cards.ToxicCard.Name";
                public const string Description = "Gameplay.Cards.ToxicCard.Description";
            }
        }
        public static class Slots
        {
            public static class DefaultSlot
            {
                public const string Name = "Gameplay.Slots.DefaultSlot.Name";
                public const string Description = "Gameplay.Slots.DefaultSlot.Description";
            }
            public static class ToxicSlot
            {
                public const string Name = "Gameplay.Slots.ToxicSlot.Name";
                public const string Description = "Gameplay.Slots.ToxicSlot.Description";
            }
            public static class BrightSlot
            {
                public const string Name = "Gameplay.Slots.BrightSlot.Name";
                public const string Description = "Gameplay.Slots.BrightSlot.Description";
            }
        }
    }
}
